### ISSUE TITLE
_Major_ issue with kernel!!!!

### ISSUE THREAD

**Issue by nv-vn** [GruntTheDivine/infinity#1]
### THIS IS AN EXTREMELY IMPORTANT ISSUE AND MUST BE ADDRESSED IMMEDIATELY!!!!
The wallpaper in this kernel (`kernel/bin/initrd/lib/infinity/avril.raster`) must be replaced, as it is not an asian woman. Please consider changing this. This is an important issue and needs to be addressed at once. Thank you very much, nv.

**Comment by GruntTheDivine** [comment]
Thank you for addressing your concern. This will be forwarded to our Ministry of Racial Equality who will verify that all images contained within this repository fulfill our racial quotas. The Ministry of Racial Equality's mission is to ensure that all minorities are represented equally and to diminish racial discrimination. It may take 4-6 weeks for the Ministry of Racial Equality to process your request.

Thank you, 
     The Ministry of Racial Equality

**Comment by nv-vn** [comment]
CAN U PLZ CHANGE THE BACKGROUND TO MY WAIFU!!!!11!!1!!

**Comment by DarinBoyer** [comment]
I feel like if you're under the age of 17 rather than mature girls it should be a disney star(preferably Rowan Blanchard or Peyton List). 

This must be bumped to at most emergency!!!!1!!

**Comment by nv-vn** [comment]
@DarinBoyer
Hmm, very interesting point. This will take much discussion. @GruntTheDivine We need to hear your opinion on this idea

**Comment by JacobMisirian** [comment]
This is a very important issue. I just got off the phone with Jessie Jackson and he says that if you do not change the offensive "whites only" kernel he will personally lead a protest march against your organization. He also said to "1v1 me on rust" because he was "3 good 5 u m9". Heed the advice of Reverend Jackson @GruntTheDivine... or else!

**Comment by nv-vn** [comment]
Glad to see other people supporting the cause. I find it _EXTREMELY_ problematic that this has not been changed yet. I am going to start a petition and kickstarter. Please help fund this change! Please donate bitcoins to me and like my facebook status about this issue!

**Comment by JacobMisirian** [comment]
#voteforhillary2016
#December7th1941NeverForgiveNeverForget

**Comment by nv-vn** [comment]
Okay here is my suggestion for the new background: https://i.4cdn.org/s/1428355113273.jpg
What do you guys think?

**Comment by nv-vn** [comment]
What did you use to export the avril.raster image/what format is it?

**Comment by GruntTheDivine** [comment]
The image is encoded as a 800x600x32 raw RGB bitmap. I just hacked out some C# code to encode it (This is the code https://gist.github.com/GruntTheDivine/77c91325537b6dba0e84 )

**Comment by nv-vn** [comment]
Oh thanks. Time to make my own distro :P

**Comment by nv-vn** [comment]
![It works!](https://i.imgur.com/AH0WnxM.png)
